# Generated by Django 4.2.1 on 2023-05-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soultions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='len',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
